import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "../styles/globals.scss";
import { Footer } from "@/components";

const open_sans = Open_Sans({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin", "cyrillic"],
  display: "swap",
  variable: "--font-open-sans",
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="uk">
      <body className={`${open_sans.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
